trigger:
  - main

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"

stages:
  - stage: BuildAndPush
    displayName: Build and push image
    jobs:
      - job: BuildAndPush
        displayName: Build and push image
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: "Docker Hub Account"
              repository: "ferraroluc/flask-hello-world"
              command: "buildAndPush"
              Dockerfile: "**/Dockerfile"
              tags: |
                $(tag)
                latest
